### PR TITLE
Update to CCTZ version 2.3

### PR DESCRIPTION
**Pull request by Wambou**
Hi,

I just updated the recipe and tried it on my project, so sending a pull request is easy now.

Regards.

P.S.: I seem to miss something, I always have trouble with appveyor when I update versions, what am I missing ?

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @Wambou !

I've re-triggered your PR over branch testing/2.3

Thanks for your contribution!

**Comment by Wambou** [comment]
It seems to work better.
Thanks for the answer.

Edit:
The error is a bit strange, it looks like the one reported here [https://github.com/google/cctz/issues/96](https://github.com/google/cctz/issues/96), which was fixed on March 19.
Version 2.3 was released on April 4, some investigation needed...

**Comment by uilianries** [comment]
The problem is related to Mac framework. Let's wait for CI result now

**Comment by uilianries** [comment]
Hi @Wambou, your PR is okay now. I gonna merge it and promote into stable branch.

Thanks for your contribution!

**Comment by Wambou** [comment]
Thanks for your help.
I did not have time to look on it...

**Pull request merged**
