### PR TITLE
Update recipe and docker images

### PR DESCRIPTION
**Pull request by danimtb**
- Updated docker images to use new 'conanio' ones.
- Apply recipe naming convention

Please, remove outdated packages:
image

cc/ @uilianries

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
I'm waiting for CCTZ build to remove outdated packages.

**Comment by uilianries** [comment]
All outdated package have been removed.

cctz/2.2@bincrafters/stable

**Pull request merged**
